name: phone_check
description: A phone checking app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0+1
  fl_chart: ^0.64.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  device_info_plus: ^9.1.0
  battery_plus: ^4.0.2
  sensors_plus: ^3.1.0
  connectivity_plus: ^4.0.2
  geolocator: ^10.1.0
  permission_handler: ^10.4.5
  path_provider: ^2.1.1
  timelines: ^0.1.0
  sleek_circular_slider: ^2.0.1
  material_symbols_icons: ^4.2719.1
  font_awesome_flutter: ^10.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
